//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquestrianCompetitions
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquestrianCompetitionsEntities : DbContext
    {
        private static EquestrianCompetitionsEntities context;
        public EquestrianCompetitionsEntities()
            : base("name=EquestrianCompetitionsEntities")
        {
        }
        public static EquestrianCompetitionsEntities GetContext()
        {
            if (context == null)
                context = new EquestrianCompetitionsEntities();

            return context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breeds> Breeds { get; set; }
        public virtual DbSet<Coaches> Coaches { get; set; }
        public virtual DbSet<Competitions> Competitions { get; set; }
        public virtual DbSet<Disqualifications> Disqualifications { get; set; }
        public virtual DbSet<Horses> Horses { get; set; }
        public virtual DbSet<Jockeys> Jockeys { get; set; }
        public virtual DbSet<Judges> Judges { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Races> Races { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<RaceMembers> RaceMembers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CompetitionInfoView> CompetitionInfoView { get; set; }
        public virtual DbSet<HorseInfoView> HorseInfoView { get; set; }
        public virtual DbSet<JockeyInfoView> JockeyInfoView { get; set; }
        public virtual DbSet<MemberInfoView> MemberInfoView { get; set; }
        public virtual DbSet<RaceScoreInfoView> RaceScoreInfoView { get; set; }
        public virtual DbSet<RaceView> RaceView { get; set; }
        public virtual DbSet<UserView> UserView { get; set; }
    }
}
