//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquestrianCompetitions
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorseInfoView
    {
        public int id { get; set; }
        public string horse { get; set; }
        public int age { get; set; }
        public string breed { get; set; }
        public Nullable<int> performanceCount { get; set; }
        public string coach { get; set; }
    }
}
