//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquestrianCompetitions
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInfoView
    {
        public string fio { get; set; }
        public string rank { get; set; }
        public decimal weight { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string distance { get; set; }
    }
}
