//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquestrianCompetitions
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public string login { get; set; }
        public string password { get; set; }
        public int role { get; set; }
        public int id { get; set; }
        public string fio { get; set; }
        public System.DateTime birthday { get; set; }
        public string rank { get; set; }
        public decimal weight { get; set; }
    }
}
